version: "3.8"

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
